# yaml for parcel-based time-series dataset for deep learning

# name for this config
config_name:
  'dijon_train'

# label raster map in raster format (type for pixel values)
label_path:
  'K:\FF\application_dataset\2020-france-agri-grid\parcel_dirong\polygon_rasterize\parcel_dirong_maincrop_removesmall_utm_polygon.tif'

# time-series raster images
raster_list:
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190304_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190309_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190314_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190319_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190324_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190329_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190403_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190408_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190413_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190418_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190423_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190428_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190503_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190508_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190513_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190518_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190523_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190528_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190602_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190607_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190612_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190617_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190622_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190627_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190702_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190707_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190712_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190717_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190722_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190727_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190801_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190806_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190811_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190816_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190821_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190826_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190831_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190905_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190910_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190915_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190920_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190925_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190930_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20191005_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20191010_masked_10m.tif'
#  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20191015_masked_10m.tif'
  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20191020_masked_10m.tif'
  - 'K:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20191025_masked_10m.tif'

# where to store dataset
result_folder:
  'K:\FF\application_dataset\2020-france-agri-grid\s2_l2a_tif_masked'

# where to store temp data
temp_folder:
  'K:\FF\application_dataset\2020-france-agri-grid\temp'

# indicating no data values for time-series raster
no_data_raster: 0
# patch size
patch_size: 32
# min percentage for sample type in a patch
min_pixel_percent: 0.01

