# yaml for parcel-based time-series dataset for deep learning

# name for this config
config_name:
  'dijon'

# label raster map in raster format (type for pixel values)
label_raster:
  'H:\FF\application_dataset\2020-france-agri\parcel_dirong\polygon\parcel_dirong_maincrop_removesmall_utm_label.tif'

# time-series raster images
raster_list:
  - 'H:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190304_masked_10m.tif'
  - 'H:\FF\application_dataset\2020-france-agri\s2_l2a_tif_masked\10m\L1C_T31TFN_20190309_masked_10m.tif'

# where to store dataset
result_folder:
  '.\result'

# where to store temp data
temp_folder:
  '.\temp'

# indicating no data values for time-series raster
no_data_raster: 0
# patch size
patch_size: 32
# min percentage for sample type in a patch
min_pixel_percent: 0.01

